"""Loading golden fixtures.

Fixtures are described by a manifest under ``fixtures/golden-manifests/`` and
their tensors live under ``fixtures/<name>/``. The weight blobs themselves are
not committed -- they are regenerated by ``scripts/make_golden_fixture.py``,
which is also what verifies the source checkpoint's SHA-256 before touching
it. The manifest *is* committed, so provenance and per-tensor digests are
always under review even when the bytes are not.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from ..config import Mamba2Config
from ..errors import FixtureError

__all__ = ["GoldenFixture", "available_fixtures", "fixtures_root", "load_fixture"]


def fixtures_root() -> Path:
    """Locate the ``fixtures/`` directory of a source checkout."""
    here = Path(__file__).resolve()
    for parent in here.parents:
        candidate = parent / "fixtures"
        if candidate.is_dir():
            return candidate
    raise FixtureError("could not locate the fixtures/ directory")


@dataclass(frozen=True)
class GoldenFixture:
    """One fixture: its manifest, config, weights and deterministic inputs."""

    name: str
    manifest: dict[str, Any]
    config: Mamba2Config
    directory: Path

    @property
    def is_real_checkpoint(self) -> bool:
        """Whether this came from a real trained checkpoint rather than a seed."""
        return "source_sha256" in self.manifest

    def _load(self, filename: str) -> dict[str, Any]:
        path = self.directory / filename
        if not path.is_file():
            raise FixtureError(
                f"{path} is missing. Regenerate it with:\n"
                f"  python scripts/make_golden_fixture.py"
                + ("  --niverel" if self.name == "niverel" else "")
            )
        from safetensors.numpy import load_file

        return dict(load_file(str(path)))

    def weights(self) -> dict[str, Any]:
        filename = "block.safetensors" if self.name == "niverel" else "weights.safetensors"
        return self._load(filename)

    def torch_weights(self, dtype: Any = None, device: Any = None) -> dict[str, Any]:
        import torch

        out = {}
        for key, value in self.weights().items():
            tensor = torch.from_numpy(value)
            if dtype is not None:
                tensor = tensor.to(dtype)
            if device is not None:
                tensor = tensor.to(device)
            out[key] = tensor
        return out

    def inputs(self) -> dict[str, Any]:
        return self._load("inputs.safetensors")

    def torch_inputs(self, dtype: Any = None, device: Any = None) -> dict[str, Any]:
        import torch

        out = {}
        for key, value in self.inputs().items():
            tensor = torch.from_numpy(value)
            if key != "seq_idx" and dtype is not None:
                tensor = tensor.to(dtype)
            if device is not None:
                tensor = tensor.to(device)
            out[key] = tensor
        return out


def available_fixtures() -> list[str]:
    root = fixtures_root() / "golden-manifests"
    if not root.is_dir():
        return []
    return sorted(p.stem for p in root.glob("*.json"))


def load_fixture(name: str) -> GoldenFixture:
    root = fixtures_root()
    manifest_path = root / "golden-manifests" / f"{name}.json"
    if not manifest_path.is_file():
        raise FixtureError(
            f"unknown fixture {name!r}; available: {available_fixtures()}. "
            "Run scripts/make_golden_fixture.py to build them."
        )
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    config = Mamba2Config.from_dict(manifest["config"])
    return GoldenFixture(name=name, manifest=manifest, config=config, directory=root / name)
